{{- if .Values.migrations.job.enabled }}
{{- $jobEnv := mergeOverwrite (dict) .Values.env (.Values.migrations.job.env | default dict) -}}
{{- $jobEnvSecrets := mergeOverwrite (dict) .Values.envSecrets (.Values.migrations.job.envSecrets | default dict) -}}
{{- $jobEnvConfigMaps := mergeOverwrite (dict) .Values.envConfigMaps (.Values.migrations.job.envConfigMaps | default dict) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "..fullname" . }}-db-up
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migrations.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "..labels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: db-up
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["/broker", "db-up"]
          env:
            - name: DB_MIGRATE
              value: "true"
            {{- range $k, $v := $jobEnv }}
            {{- if ne $k "DB_MIGRATE" }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
            {{- end }}
            {{- range $k, $v := $jobEnvSecrets }}
            {{- if ne $k "DB_MIGRATE" }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: "{{ $v.name }}"
                  key: "{{ $v.key }}"
            {{- end }}
            {{- end }}
            {{- range $k, $v := $jobEnvConfigMaps }}
            {{- if ne $k "DB_MIGRATE" }}
            - name: {{ $k }}
              valueFrom:
                configMapKeyRef:
                  name: "{{ $v.name }}"
                  key: "{{ $v.key }}"
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
